server:
  http:
    addr: 0.0.0.0:6666
    timeout: 1800s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: game:smp5H3kMJ24Bcp5F@tcp(127.0.0.1:3306)/game?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_key: 219e85679b38e65b59320ac7e1b23e90 # md5 dhbmachine